import { firebaseConfig } from './firebase-config.js';
import { initializeApp } from 'https://www.gstatic.com/firebasejs/10.14.1/firebase-app.js';
import { getAuth, onAuthStateChanged, signInWithEmailAndPassword, createUserWithEmailAndPassword, updateProfile, sendPasswordResetEmail, signOut } from 'https://www.gstatic.com/firebasejs/10.14.1/firebase-auth.js';
import { getFirestore, collection, doc, setDoc, getDoc, updateDoc, addDoc, query, where, orderBy, limit, onSnapshot, serverTimestamp, getDocs, arrayUnion } from 'https://www.gstatic.com/firebasejs/10.14.1/firebase-firestore.js';
import { getStorage, ref, uploadBytes, getDownloadURL } from 'https://www.gstatic.com/firebasejs/10.14.1/firebase-storage.js';

const app = initializeApp(firebaseConfig);
const auth = getAuth(app);
const db = getFirestore(app);
const storage = getStorage(app);
const $ = id => document.getElementById(id);
const state = { user:null, profile:null, selected:null, unsubscribeMessages:null, unsubscribeUsers:null, users:[], authMode:'login', call:null, localStream:null, pc:null };

function toast(text){ const el=$('toast'); if(!el)return; el.textContent=text; el.classList.add('show'); clearTimeout(window.__toast); window.__toast=setTimeout(()=>el.classList.remove('show'),2800); }
function initials(name='A'){ return name.trim().split(/\s+/).slice(0,2).map(x=>x[0]).join('').toUpperCase() || 'A'; }
function statusText(s){ return ({online:'Онлайн',away:'Отошёл',dnd:'Не беспокоить',invisible:'Невидимый',offline:'Оффлайн'})[s] || 'Оффлайн'; }
function cid(a,b){ return [a,b].sort().join('_'); }
function esc(v=''){ const d=document.createElement('div'); d.textContent=String(v); return d.innerHTML; }
function time(ts){ return ts?.toDate ? ts.toDate().toLocaleTimeString([], {hour:'2-digit',minute:'2-digit'}) : '…'; }
function errorText(code){ return ({'auth/invalid-credential':'Неверный email или пароль','auth/email-already-in-use':'Email уже используется','auth/weak-password':'Пароль должен содержать минимум 6 символов','auth/invalid-email':'Некорректный email','auth/network-request-failed':'Ошибка сети','auth/too-many-requests':'Слишком много попыток. Попробуйте позже.'}[code] || `Ошибка: ${code||'неизвестная'}`); }
function showAuth(){ $('authView').classList.remove('hidden'); $('appView').classList.add('hidden'); }
function showApp(){ $('authView').classList.add('hidden'); $('appView').classList.remove('hidden'); }

$('toggleAuth').onclick=()=>{ state.authMode=state.authMode==='login'?'register':'login'; document.querySelectorAll('.register-only').forEach(x=>x.style.display=state.authMode==='register'?'block':'none'); $('authSubmitText').textContent=state.authMode==='register'?'Создать аккаунт':'Войти'; $('toggleAuth').textContent=state.authMode==='register'?'Уже есть аккаунт? Войти':'Нет аккаунта? Зарегистрироваться'; };
document.querySelectorAll('.register-only').forEach(x=>x.style.display='none');
$('forgotPassword').onclick=async()=>{ const email=$('email').value.trim(); if(!email){$('authError').textContent='Сначала введите email';return;} try{await sendPasswordResetEmail(auth,email);toast('Письмо для восстановления отправлено');}catch(e){$('authError').textContent=errorText(e.code);}};
$('authForm').onsubmit=async e=>{ e.preventDefault(); $('authError').textContent=''; try{ const email=$('email').value.trim().toLowerCase(), password=$('password').value; if(state.authMode==='login'){await signInWithEmailAndPassword(auth,email,password);} else { const cred=await createUserWithEmailAndPassword(auth,email,password); const name=$('displayName').value.trim()||email.split('@')[0]; await updateProfile(cred.user,{displayName:name}); await setDoc(doc(db,'users',cred.user.uid),{uid:cred.user.uid,email,displayName:name,displayNameLower:name.toLowerCase(),status:'online',createdAt:serverTimestamp(),lastSeen:serverTimestamp()}); } }catch(e){$('authError').textContent=errorText(e.code);} };

onAuthStateChanged(auth, async user=>{ if(state.unsubscribeUsers)state.unsubscribeUsers(); if(state.unsubscribeMessages)state.unsubscribeMessages(); state.user=user; if(!user){state.profile=null;state.selected=null;showAuth();return;} showApp(); try{await ensureProfile(); await loadProfile(); subscribeUsers();}catch(e){toast('Ошибка подключения к базе: '+e.message);} });
async function ensureProfile(){ const r=doc(db,'users',state.user.uid), s=await getDoc(r); const name=state.user.displayName||state.user.email?.split('@')[0]||'Пользователь'; if(!s.exists()) await setDoc(r,{uid:state.user.uid,email:state.user.email||'',displayName:name,displayNameLower:name.toLowerCase(),status:'online',createdAt:serverTimestamp(),lastSeen:serverTimestamp()}); else await updateDoc(r,{lastSeen:serverTimestamp(),status:'online'}); }
async function loadProfile(){ const s=await getDoc(doc(db,'users',state.user.uid)); state.profile=s.data()||{}; $('myName').textContent=state.profile.displayName||'Пользователь'; $('myAvatar').textContent=initials(state.profile.displayName); $('myStatus').textContent=statusText(state.profile.status); $('settingsName').value=state.profile.displayName||''; $('settingsStatus').value=state.profile.status||'online'; }

function subscribeUsers(){ if(state.unsubscribeUsers)state.unsubscribeUsers(); const q=query(collection(db,'users'),orderBy('displayNameLower'),limit(200)); state.unsubscribeUsers=onSnapshot(q,snap=>{state.users=snap.docs.map(d=>d.data()).filter(u=>u.uid!==state.user.uid); renderUsers();},e=>toast('Ошибка загрузки пользователей: '+e.message)); }
$('userSearch').oninput=renderUsers;
function renderUsers(){ const term=$('userSearch').value.trim().toLowerCase(); const list=state.users.filter(u=>!term||(u.displayNameLower||'').includes(term)||(u.email||'').toLowerCase().includes(term)); const box=$('contactList'); box.innerHTML=''; if(!list.length){box.innerHTML='<div class="muted" style="padding:20px">Пользователи не найдены</div>';return;} list.forEach(u=>{const row=document.createElement('button'); row.type='button'; row.className='list-item'+(state.selected?.uid===u.uid?' active':''); row.dataset.uid=u.uid; row.innerHTML=`<div class="avatar">${esc(initials(u.displayName))}</div><div class="list-text"><strong>${esc(u.displayName||u.email)}</strong><span>${esc(statusText(u.status))}</span></div><i class="online-dot" style="display:${u.status==='online'?'block':'none'}"></i>`; row.onclick=()=>selectUser(u); box.appendChild(row);});}

async function selectUser(user){ state.selected=user; renderUsers(); $('detailsPanel').classList.remove('hidden'); $('detailsAvatar').textContent=initials(user.displayName); $('detailsName').textContent=user.displayName||user.email; $('detailsStatus').textContent=statusText(user.status); $('chatHeader').className='chat-head'; $('chatHeader').innerHTML=`<div class="chat-title"><div class="avatar">${esc(initials(user.displayName))}</div><div><strong>${esc(user.displayName||user.email)}</strong><div class="muted">${esc(statusText(user.status))}</div></div></div>`; $('messageForm').classList.remove('hidden'); subscribeMessages(); }
function subscribeMessages(){ if(state.unsubscribeMessages)state.unsubscribeMessages(); const id=cid(state.user.uid,state.selected.uid); const q=query(collection(db,'conversations',id,'messages'),orderBy('createdAt','asc'),limit(500)); state.unsubscribeMessages=onSnapshot(q,snap=>{const box=$('messages');box.innerHTML='';if(snap.empty){box.innerHTML='<div class="empty-state"><div class="empty-icon">👋</div><p>Напишите первое сообщение</p></div>';return;} snap.docs.forEach(d=>renderMessage(box,{id:d.id,...d.data()}));box.scrollTop=box.scrollHeight; markIncomingRead(snap.docs);},e=>{boxError(e);}); }
function boxError(e){ $('messages').innerHTML=`<div class="empty-state"><h3>Ошибка загрузки сообщений</h3><p>${esc(e.message)}</p></div>`; toast('Ошибка сообщений: '+e.message); }
async function markIncomingRead(docs){ if(!state.selected)return; const updates=docs.filter(d=>d.data().senderId===state.selected.uid&&!d.data().readBy?.includes(state.user.uid)).slice(-50); await Promise.all(updates.map(d=>updateDoc(d.ref,{readBy:arrayUnion(state.user.uid)}).catch(()=>{}))); }
function renderMessage(box,m){ const mine=m.senderId===state.user.uid; const row=document.createElement('div'); row.className='bubble-row '+(mine?'mine':''); let body=esc(m.text||''); if(m.type==='image'&&m.url)body=`<img src="${esc(m.url)}" alt="Фото" style="max-width:260px;border-radius:10px;display:block">`; if(m.type==='file'&&m.url)body=`<a class="file-card" href="${esc(m.url)}" target="_blank" rel="noopener">📎 ${esc(m.fileName||'Файл')}</a>`; row.innerHTML=`<div class="bubble">${body}<span class="time">${time(m.createdAt)}</span>${mine?`<span class="status">${m.readBy?.includes(state.selected?.uid)?'✓✓':'✓'}</span>`:''}</div>`;box.appendChild(row); }

$('messageForm').onsubmit=async e=>{e.preventDefault();const input=$('messageInput'),text=input.value.trim();if(!text||!state.selected)return;input.disabled=true;try{await sendMessage({type:'text',text});input.value='';}catch(err){toast('Не удалось отправить: '+err.message);}finally{input.disabled=false;input.focus();}};
async function sendMessage(data){if(!state.user||!state.selected)throw new Error('Чат не выбран');const id=cid(state.user.uid,state.selected.uid);const c=doc(db,'conversations',id);const base={id,members:[state.user.uid,state.selected.uid],updatedAt:serverTimestamp(),lastMessage:data.text||data.fileName||'Файл',lastSenderId:state.user.uid};await setDoc(c,base,{merge:true});await addDoc(collection(c,'messages'),{...data,senderId:state.user.uid,readBy:[state.user.uid],createdAt:serverTimestamp()});}
$('attachButton').onclick=()=>$('fileInput').click();
$('fileInput').onchange=async()=>{const file=$('fileInput').files?.[0];$('fileInput').value='';if(!file||!state.selected)return;try{toast('Загрузка файла...');const safe=file.name.replace(/[^a-zA-Z0-9._-]/g,'_');const path=`chat-files/${cid(state.user.uid,state.selected.uid)}/${Date.now()}_${safe}`;const r=ref(storage,path);await uploadBytes(r,file);const url=await getDownloadURL(r);await sendMessage({type:file.type.startsWith('image/')?'image':'file',text:'',url,fileName:file.name});toast('Файл отправлен');}catch(e){toast('Ошибка загрузки: '+e.message);}};
$('emojiButton').onclick=()=>{const i=$('messageInput');i.value+=(i.value?' ':'')+'😊';i.focus();};

$('profileButton').onclick=()=>$('settingsModal').classList.remove('hidden');$('settingsButton').onclick=()=>$('settingsModal').classList.remove('hidden');$('closeSettings').onclick=()=>$('settingsModal').classList.add('hidden');
$('saveSettings').onclick=async()=>{try{const name=$('settingsName').value.trim()||'Пользователь',status=$('settingsStatus').value;await updateProfile(state.user,{displayName:name});await updateDoc(doc(db,'users',state.user.uid),{displayName:name,displayNameLower:name.toLowerCase(),status,lastSeen:serverTimestamp()});await loadProfile();$('settingsModal').classList.add('hidden');toast('Настройки сохранены');}catch(e){toast('Ошибка сохранения: '+e.message);}};
$('logoutButton').onclick=()=>signOut(auth);
$('darkMode').onchange=e=>{document.body.classList.toggle('dark',e.target.checked);localStorage.setItem('agent-dark',e.target.checked?'1':'0');}; if(localStorage.getItem('agent-dark')==='1'){ $('darkMode').checked=true;document.body.classList.add('dark'); }

$('callAudio').onclick=()=>startCall(false);$('callVideo').onclick=()=>startCall(true);$('hangupButton').onclick=hangup;
async function startCall(video){if(!state.selected)return;try{state.call={id:crypto.randomUUID(),video};$('callModal').classList.remove('hidden');$('callTitle').textContent=(video?'Видеозвонок: ':'Аудиозвонок: ')+(state.selected.displayName||state.selected.email);$('callState').textContent='Запрашиваем доступ к микрофону...';state.localStream=await navigator.mediaDevices.getUserMedia({audio:true,video});$('localVideo').srcObject=state.localStream;state.pc=new RTCPeerConnection({iceServers:[{urls:'stun:stun.l.google.com:19302'}]});state.localStream.getTracks().forEach(t=>state.pc.addTrack(t,state.localStream));state.pc.ontrack=e=>$('remoteVideo').srcObject=e.streams[0];const offer=await state.pc.createOffer();await state.pc.setLocalDescription(offer);await setDoc(doc(db,'calls',state.call.id),{callerId:state.user.uid,calleeId:state.selected.uid,video,offer:{type:offer.type,sdp:offer.sdp},status:'ringing',createdAt:serverTimestamp()});$('callState').textContent='Ожидание ответа...';}catch(e){toast('Звонок не запущен: '+e.message);await hangup();}}
async function hangup(){if(state.localStream)state.localStream.getTracks().forEach(t=>t.stop());if(state.pc)state.pc.close();state.localStream=null;state.pc=null;$('callModal').classList.add('hidden');}
window.addEventListener('beforeunload',()=>{if(state.user)updateDoc(doc(db,'users',state.user.uid),{status:'offline',lastSeen:serverTimestamp()}).catch(()=>{});});
if('serviceWorker' in navigator)navigator.serviceWorker.register('./sw.js').catch(()=>{});
