import { getFirestore, collection, doc, query, where, limit, onSnapshot, getDoc, updateDoc, serverTimestamp, setDoc, getDocs } from 'https://www.gstatic.com/firebasejs/10.14.1/firebase-firestore.js';
import { getAuth } from 'https://www.gstatic.com/firebasejs/10.14.1/firebase-auth.js';
import { firebaseConfig } from './firebase-config.js';
import { initializeApp, getApps } from 'https://www.gstatic.com/firebasejs/10.14.1/firebase-app.js';
const app=getApps().length?getApps()[0]:initializeApp(firebaseConfig);const db=getFirestore(app),auth=getAuth(app);const $=id=>document.getElementById(id);let incomingStop=null;
const uid=()=>auth.currentUser?.uid;function toast(t){const x=$('toast');if(!x)return;x.textContent=t;x.classList.add('show');clearTimeout(window.__enhToast);window.__enhToast=setTimeout(()=>x.classList.remove('show'),2600)}
function installGroups(){const tabs=document.querySelector('.tabs');if(!tabs||document.getElementById('groupButton'))return;const b=document.createElement('button');b.id='groupButton';b.className='tab';b.textContent='＋';b.title='Создать группу';b.onclick=async()=>{const name=prompt('Название группы');if(!name?.trim())return;const emails=(prompt('Email участников через запятую')||'').split(',').map(x=>x.trim().toLowerCase()).filter(Boolean);const users=await Promise.all(emails.map(async e=>{const s=await getDocs(query(collection(db,'users'),where('email','==',e),limit(1)));return s.empty?null:s.docs[0].data()}));const members=[uid(),...users.filter(Boolean).map(x=>x.uid).filter(x=>x!==uid())];if(members.length<2)return toast('Участники не найдены');const r=doc(collection(db,'conversations'));await setDoc(r,{id:r.id,type:'group',name:name.trim(),members,ownerId:uid(),createdAt:serverTimestamp(),updatedAt:serverTimestamp(),lastMessage:'Группа создана'});toast('Группа создана')};tabs.appendChild(b)}
function installIncoming(){setTimeout(()=>{const u=uid();if(!u)return;const q=query(collection(db,'calls'),where('calleeId','==',u),where('status','==','ringing'),limit(1));incomingStop=onSnapshot(q,async s=>{if(s.empty)return;const d=s.docs[0],c=d.data();const us=await getDoc(doc(db,'users',c.callerId));const p=us.data()||{};if(!confirm(`${p.displayName||'Пользователь'} звонит.\nOK — принять после открытия окна звонка, Отмена — отклонить.`)){await updateDoc(d.ref,{status:'declined'});return}toast('Входящий звонок принят. Откройте чат звонящего для управления звонком.')})},1500)}
function ready(){if(window.__agentEnhancementReady)return;window.__agentEnhancementReady=true;installGroups();installIncoming()}window.addEventListener('load',ready);setTimeout(ready,1800);
